name: upload an artifact

on: [pull_request]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is not okay!" >> stored
      - uses: actions/upload-artifact@v2
        with:
          name: bin
          path: stored
